fix: update environment variable files in Docker Compose configurations
cryptlex/cryptlex-on-premise pull request #2
Opened 2024-02-29 10:31 UTC by saalim-mushtaq

2024-02-29 10:39 UTC, saalim-mushtaq commented
@adnan-kamili

2024-03-01 07:09 UTC, adnan-kamili commented on .env
> +WEB_API_DOMAIN=api-test.cryptlex.io
why is the cryptlex.io domain being used here?

2024-03-01 07:09 UTC, adnan-kamili commented on .env
> -GOOGLE_CLIENT_ID=PASTE_GOOGLE_CLIENT_ID
why is this removed

2024-03-01 07:11 UTC, adnan-kamili commented on web-api.env
> +APPLICATION_LICENSE_KEY=A2CE5C-F4A70D-47FF85-261A3B-ACF503-8685C6
why has this file been changed? this leakes the license key and secret in a public repo

2024-03-01 07:13 UTC, adnan-kamili commented on docker-compose.yml
> +      - traefik.backend=cryptlex/cryptlex-admin-portal
please clarify why backend uses this value? Have we used this pattern anywhere in the file

2024-03-01 07:14 UTC, adnan-kamili commented on docker-compose.yml
> + admin-portal:
the indentation is incorrect which makes the file invalid. YAML is sensitive to indentation

2024-03-01 07:15 UTC, adnan-kamili requested changes
please check comments

2024-03-06 05:49 UTC, adnan-kamili commented on docker-compose.yml
> +
remove this extra line

2024-03-06 05:49 UTC, adnan-kamili commented on docker-compose.yml
> +
remove this extra line

2024-03-06 05:49 UTC, adnan-kamili commented on docker-compose.yml
> +
remove this extra line

2024-03-06 05:50 UTC, adnan-kamili requested changes
please check comments

2024-09-23 10:49 UTC, closed without merging